#!/bin/bash

set -e
set -o pipefail

TMP_DIR=/tmp/banana-build

# To deploy, we build the blog and push to remote master.
# Github will serve the site from there.

git_ref () {
  # Prints the current branch name or the sha
  git symbolic-ref --short HEAD 2>/dev/null \
    || git rev-parse HEAD
}

is_clean () {
  # Returns non-zero if the working dir is dirty
  git diff-index --quiet HEAD --
}

last_ref=$(git_ref)

rm -rf $TMP_DIR
banana build --clean
mv _build $TMP_DIR

git add .
git stash

git checkout master
git pull --rebase origin master

if [[ ! -f index.html ]]; then
  echo "error: not in the build dir"
  exit 1
fi

ls | grep -v CNAME | xargs rm -rf
mv $TMP_DIR/* .
rm -rf $TMP_DIR

git add .
is_clean || (
  git commit -m 'Deploy site'
  git push origin master
)

git checkout $last_ref
git stash pop
